version: '3.9'
services:
  mysql:
    image: mysql:8.4
    container_name: perf_lab_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
    ports:
      - "3306:3306"
    command: ["mysqld","--performance_schema=ON","--innodb_buffer_pool_size=512M","--slow_query_log=1","--long_query_time=0.2"]
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ../schema:/docker-entrypoint-initdb.d/schema
      - ../procedures/naive:/docker-entrypoint-initdb.d/procedures_naive
