name: Block AI-Generated Commits

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    name: Verify No AI Attribution in Commits

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit messages
        run: |
          echo "Checking commit messages for AI attribution..."

          # Get the range of commits to check
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            COMMITS=$(git log --pretty=format:"%H" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          else
            # For push events, check the pushed commits
            COMMITS=$(git log --pretty=format:"%H" ${{ github.event.before }}..${{ github.event.after }})
          fi

          # Patterns to block
          BLOCKED_PATTERNS=(
            "Generated with \[Claude Code\]"
            "Co-Authored-By: Claude"
            "🤖 Generated with"
            "claude.com/claude-code"
          )

          FOUND_VIOLATION=false

          for commit in $COMMITS; do
            MESSAGE=$(git log --format=%B -n 1 $commit)

            for pattern in "${BLOCKED_PATTERNS[@]}"; do
              if echo "$MESSAGE" | grep -qi "$pattern"; then
                echo "❌ BLOCKED: Commit $commit contains AI attribution"
                echo "   Pattern found: $pattern"
                echo "   Commit message:"
                echo "$MESSAGE" | head -10
                echo ""
                FOUND_VIOLATION=true
              fi
            done
          done

          if [ "$FOUND_VIOLATION" = true ]; then
            echo ""
            echo "================================"
            echo "❌ COMMIT BLOCKED"
            echo "================================"
            echo "One or more commits contain AI-generated attribution."
            echo "Please remove AI attribution from commit messages and try again."
            echo ""
            echo "To fix: git rebase -i and edit the commit messages"
            exit 1
          fi

          echo "✅ All commits passed: No AI attribution found"
