name: Repository Statistics

# Run this once per day at 11 PM UTC to keep data current
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:  # Allow manual triggering

jobs:
  repository-stats:
    name: Collect Repository Stats
    runs-on: ubuntu-latest
    steps:
      - name: Collect and analyze repository traffic stats
        uses: jgehrcke/github-repo-stats@v1.5.0
        with:
          # GitHub token with 'repo' scope
          ghtoken: ${{ secrets.STATS_TOKEN }}

          # Optional: uncomment to track a different repository
          # repository: owner/repo-name

          # Branch where data and reports will be stored
          databranch: github-repo-stats

          # Optional: enable if you want to serve reports via GitHub Pages
          # ghpagesprefix: https://YOUR-USERNAME.github.io/YOUR-REPO-NAME
